### ISSUE TITLE
Help topics for Derek

### ISSUE THREAD

**Issue by alexellis** [alexellis/derek#109]
## Expected Behaviour

There are often behaviors demonstrated by new contributors or specific questions to which we need to answer in almost the same, verbatim way:

* Join Slack here to chat more https://...
* Sign off your single commit using this command
* Sign off those 5 commits using this command
* Oh you're doing performance testing? You can't do that in a VM on your Mac, try this docs page: https://
* CI is broken, please check the logs
* This needs a rebase before it can be merged

## Current Behaviour

Mixed results, repetition for maintainers and contributors. 

## Possible Solution

A command like: `Derek topic: sign-off` / `Derek help topic: slack`

Automating the sign-off message could be spammy, especially if someone has a number of commits and the message is sent each time. So rather than automatic, hands-off - a "semi-automatic" way of expanding snippets would be ideal.

We could keep these in .DEREK.yml such as:

```
topics:
  name: slack-join
  alias:
   - slack
  message: |
  Thank for your interest in OpenFaaS. If you'd like to continue the discussion
  or join our regular Zoom meetings, then please sign-up at https:// .... 
```

`Derek topic: slack`
