### ISSUE TITLE
.DEREK.yml 2.0 - YAML roles

### ISSUE THREAD

**Issue by alexellis** [alexellis/derek#22]
Version 2.0 of .DEREK.yml would be:

```
roles:
  - role: curator
     actions:
       - labels
       - close_issue
       - open_issue

  - role: maintainer
     actions:
       - close_issue
       - open_issue

users:
  - name: alexellis
    roles:
      - maintainer
  - name: rgee0
    roles:
      - maintainer
      - curator

features:
 - dco_check
 - comments
```
