### ISSUE TITLE
Add contributing field to .DEREK.yml

### ISSUE THREAD

**Issue by alexellis** [alexellis/derek#87]
## Expected Behaviour

We need to be able to specify a "contributing_url" field for when Derek is used across an organisation or many repos. The "redirect" flag now means many Derek files are just redirecting to another repo for rules - at least in OpenFaaS we don't need separate contributing guides.

## Current Behaviour

I create a Markdown page with a link to the openfaas/faas contributing guide but sometimes forget and that's not a great experience because new developers get linked to a 404.

## Possible Solution

Add field `contributing_url` and use that when given, otherwise use the existing behaviour.

**Comment by alexellis** [comment]
```yaml
curators:
 - rgee0
 - alexellis
 
features:
 - dco_check
 - comments

contributing_url: https://github.com/alexellis/derek/blob/master/CONTRIBUTING.md
```
